# IT2053C Environment Configuration
# 
# USAGE INSTRUCTIONS:
# - To create this environment: conda env create -f environment.yml
# - To activate manually: conda activate IT2053C
# - To deactivate: conda deactivate
# - To update environment: conda env update -f environment.yml
#
# NOTE: This environment will NOT auto-activate. Use 'conda activate IT2053C' when needed.
#
name: IT2053C
channels:
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - appnope=0.1.4
  - astroid=3.3.10
  - asttokens=3.0.0
  - attrs=25.3.0
  - backports.zoneinfo=0.2.1
  - beautifulsoup4=4.13.4
  - bleach=6.2.0
  - bleach-with-css=6.2.0
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.6.15
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.3.2
  - cycler=0.12.1
  - debugpy=1.8.14
  - decorator=5.2.1
  - defusedxml=0.7.1
  - dill=0.4.0
  - dodgy=0.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.0
  - flake8=7.3.0
  - flake8-polyfill=1.0.2
  - fonttools=4.58.4
  - freetype=2.13.3
  - gitdb=4.0.12
  - gitpython=3.1.44
  - importlib-metadata=8.7.0
  - importlib_resources=6.5.2
  - ipykernel=6.29.5
  - ipython=9.3.0
  - ipython_pygments_lexers=1.1.1
  - ipywidgets=8.1.7
  - isort=6.0.1
  - jedi=0.19.2
  - jinja2=3.1.6
  - joblib=1.5.1
  - jsonschema=4.24.0
  - jsonschema-specifications=2025.4.1
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_pygments=0.3.0
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.7
  - krb5=1.21.3
  - lcms2=2.17
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libcxx=20.1.7
  - libdeflate=1.24
  - libedit=3.1.20250104
  - libexpat=2.7.0
  - libffi=3.4.6
  - libfreetype=2.13.3
  - libfreetype6=2.13.3
  - libgfortran=5.0.0
  - libgfortran5=14.2.0
  - libjpeg-turbo=3.1.0
  - liblapack=3.9.0
  - liblzma=5.8.1
  - libmpdec=4.0.0
  - libopenblas=0.3.30
  - libpng=1.6.49
  - libsodium=1.0.20
  - libsqlite=3.50.1
  - libtiff=4.7.0
  - libwebp-base=1.5.0
  - libxcb=1.17.0
  - libzlib=1.3.1
  - llvm-openmp=20.1.7
  - logilab-common=1.7.3
  - markupsafe=3.0.2
  - matplotlib=3.10.3
  - matplotlib-base=3.10.3
  - matplotlib-inline=0.1.7
  - mccabe=0.7.0
  - mistune=3.1.3
  - munkres=1.1.4
  - mypy_extensions=1.1.0
  - narwhals=1.43.1
  - nbclient=0.10.2
  - nbconvert=7.16.6
  - nbconvert-core=7.16.6
  - nbconvert-pandoc=7.16.6
  - nbformat=5.10.4
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - numpy=2.3.0
  - openjpeg=2.5.3
  - openssl=3.5.0
  - packaging=25.0
  - pandas=2.3.0
  - pandoc=3.7.0.2
  - pandocfilters=1.5.0
  - parso=0.8.4
  - patsy=1.0.1
  - pep8-naming=0.10.0
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.2.1
  - pip=25.1.1
  - pkgutil-resolve-name=1.3.10
  - platformdirs=4.3.8
  - plotly=6.1.2
  - pluggy=1.6.0
  - prompt-toolkit=3.0.51
  - prospector=1.17.2
  - psutil=7.0.0
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pycodestyle=2.14.0
  - pydocstyle=6.3.0
  - pyflakes=3.4.0
  - pygments=2.19.1
  - pylint=3.3.7
  - pylint-celery=0.3
  - pylint-django=2.6.1
  - pylint-flask=0.6
  - pylint-plugin-utils=0.9.0
  - pyparsing=3.2.3
  - pytest=8.4.1
  - python=3.13.5
  - python-dateutil=2.9.0.post0
  - python-dotenv=1.1.0
  - python-fastjsonschema=2.21.1
  - python-tzdata=2025.2
  - python_abi=3.13
  - pytz=2025.2
  - pyyaml=6.0.2
  - pyzmq=27.0.0
  - qhull=2020.2
  - readline=8.2
  - referencing=0.36.2
  - requirements-detector=1.4.0
  - rpds-py=0.25.1
  - scikit-learn=1.7.0
  - scipy=1.15.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - semver=3.0.4
  - setoptconf-tmp=0.3.1
  - setuptools=80.9.0
  - six=1.17.0
  - smmap=5.0.2
  - snowballstemmer=3.0.1
  - soupsieve=2.7
  - stack_data=0.6.3
  - statsmodels=0.14.4
  - threadpoolctl=3.6.0
  - tinycss2=1.4.0
  - tk=8.6.13
  - toml=0.10.2
  - tomli=2.2.1
  - tomlkit=0.13.3
  - tornado=6.5.1
  - traitlets=5.14.3
  - typing-extensions=4.14.0
  - typing_extensions=4.14.0
  - tzdata=2025b
  - wcwidth=0.2.13
  - webencodings=0.5.1
  - widgetsnbextension=4.0.14
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.23.0
  - zstd=1.5.7
  - pip:
      - iniconfig==2.1.0
