name: Test Notebook Output

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  test-notebook:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Run notebook output test
      run: |
        python test_notebook_output.py
        
    - name: Upload test artifacts (if test fails)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: notebook-test-results
        path: |
          setup-checker-executed.ipynb
          test_notebook_output.py 